### ISSUE TITLE
Edge case: Staker's total deposit and rewards can be irretrievably locked

### ISSUE THREAD

**Issue by travs** [sarcophagus-org/sarcophagus-liquidity-mining#1]
### Assumptions

USDT and USDC maintain a [global blacklist](https://cointelegraph.com/news/tether-blacklists-39-ethereum-addresses-worth-over-46-million).

I'm not 100% sure how the lists work in terms of tx rejection (I can't find the contract code right now), but I'm operating under the assumption that if someone is on one of those blacklists this causes a `transfer` from/to them to fail at the tx level.

### Issue/reproduction

1. Staker deposits USDT, USDC, DAI
2. Staker is placed on one of the blacklists or the token is paused
3. Staker tries to `withdraw` staked tokens/rewards from liquidity mining contract but the entire tx fails

The offending code is a throw inside the `transfer` lines [here](https://github.com/sarcophagus-org/liquidity-mining/blob/master/contracts/LiquidityMining.sol#L269-L275).

### Potential solution

There are several possible remedies, including implementing a `partialWithdraw` function something like this:

```
function partialWithdraw(bool withdrawUsdc, bool, withdrawUsdt, bool withdrawDai, bool withdrawSarco) {
  // conditionally withdraw each token depending on input
  // optimistic "withdraw" function could call "partialWithdraw(true,true,true,true)" internally perhaps
}
```

Alternatively, each token could have its own withdraw function.

Another possibility might be to wrap the `transfer` calls in `try / catch` and handle accordingly.

**Comment by adamgall** [comment]
Awesome forward-thinking here @travs!

I'll consider the tradeoffs of the various approaches here, and get a bugfix implemented.

Thanks for taking a look at the contract 🔥

**Comment by adamgall** [comment]
Been thinking about this a lot.

Individual stablecoin withdraws is going to involve a big refactoring, which I'm not too keen on doing.

However, I just had a new thought!

Add another `address to` parameter to `withdraw` (and probably `payout`), that indicates which address the `USDC/USDT/DAI/(SARCO)` should be sent to.

On the frontend we'll just default it to the address which is making the transaction, but if that address did end up on a `USDC/USDT` blacklist, then they can manually call `withdraw` with a fresh `address to`.

@travs do you see any issues with this approach?

**Comment by travs** [comment]
@adamgall I think that's fine! The changes look good 👍
